"""Update user and task models to use UUID primary keys

Revision ID: e77283735eac
Revises: d8bb32329d9d
Create Date: 2026-01-15 03:42:14.418615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e77283735eac'
down_revision: Union[str, Sequence[str], None] = 'd8bb32329d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tags')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'recurrence_pattern')
    op.drop_column('tasks', 'priority')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('tasks', sa.Column('priority', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='priorityenum'), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('recurrence_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tags_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('task_tags',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('task_tags_tag_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_tags_task_id_fkey')),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('task_tags_pkey'))
    )
    # ### end Alembic commands ###
